# Generated by Django 5.2.8 on 2025-11-17 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование трека')),
                ('number_of_name', models.IntegerField(verbose_name='Номер имён')),
                ('file', models.FileField(upload_to='audio/', verbose_name='Аудио файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.country', verbose_name='Страна')),
            ],
        ),
    ]
