# Generated by Django 5.2.8 on 2025-11-20 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_email'),
        ('homePage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fajr', models.PositiveIntegerField(default='0', verbose_name='Бомдод')),
                ('isha', models.PositiveIntegerField(default='0', verbose_name='Хуфтон')),
                ('tahajud', models.PositiveIntegerField(default='0', verbose_name='Тахажуд')),
                ('lesson', models.PositiveIntegerField(default='0', verbose_name='Дарс')),
                ('koran', models.PositiveIntegerField(default='0', verbose_name='Куръон')),
                ('tafakkur', models.PositiveIntegerField(default='0', verbose_name='Тафаккур')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата добавления')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.country', verbose_name='Страна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_weekly_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
