# Generated by Django 5.2.8 on 2025-11-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_weeklyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreport',
            name='fajr',
            field=models.PositiveIntegerField(default=0, verbose_name='Бомдод'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='isha',
            field=models.PositiveIntegerField(default=0, verbose_name='Хуфтон'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='koran',
            field=models.PositiveIntegerField(default=0, verbose_name='Куръон'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='lesson',
            field=models.PositiveIntegerField(default=0, verbose_name='Дарс'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='tafakkur',
            field=models.PositiveIntegerField(default=0, verbose_name='Тафаккур'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='tahajud',
            field=models.PositiveIntegerField(default=0, verbose_name='Тахажуд'),
        ),
    ]
