# Generated by Django 5.2.8 on 2025-12-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_alter_weeklyreport_fajr_alter_weeklyreport_isha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='duo',
            field=models.PositiveIntegerField(default=0, verbose_name='Дуолар'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='infok',
            field=models.PositiveIntegerField(default=0, verbose_name='Инфок'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='ishrok',
            field=models.PositiveIntegerField(default=0, verbose_name='Ишрок'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='nafl_roza',
            field=models.PositiveIntegerField(default=0, verbose_name='Мисвак'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='zikr',
            field=models.PositiveIntegerField(default=0, verbose_name='Зикрлар'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='lesson',
            field=models.PositiveIntegerField(default=0, verbose_name='Такрор'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='tahajud',
            field=models.PositiveIntegerField(default=0, verbose_name='Тахажжуд'),
        ),
    ]
