# Generated by Django 5.2.8 on 2025-12-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_weeklyreport_duo_weeklyreport_infok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='misvak',
            field=models.PositiveIntegerField(default=0, verbose_name='Мисвак'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='nafl_roza',
            field=models.PositiveIntegerField(default=0, verbose_name='Нафл роза'),
        ),
    ]
