# Generated by Django 5.2.8 on 2025-11-15 23:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('admin', 'админ'), ('chef', 'шеф'), ('administrator', 'администратор'), ('employee', 'ученик'), ('client', 'клиент')], default='employee', max_length=255, verbose_name='Тип'),
        ),
    ]
